char_map = {
    "no fighter": 0,
    "Mario": 7,
    "Donkey Kong": 8,
    "Link": 9,
    "Samus": 10,
    "Dark Samus": 11,
    "Yoshi": 12,
    "Kirby": 13,
    "Fox": 14,
    "Pikachu": 15,
    "Luigi": 16,
    "Ness": 17,
    "Captain Falcon": 18,
    "Jigglypuff": 19,
    "Peach": 20,
    "Daisy": 21,
    "Bowser": 22,
    "Ice Climbers": 23,
    "Sheik": 24,
    "Zelda": 25,
    "Dr. Mario": 26,
    "Pichu": 27,
    "Falco": 28,
    "Marth": 29,
    "Lucina": 30,
    "Young Link": 31,
    "Ganondorf": 32,
    "Mewtwo": 33,
    "Roy": 34,
    "Chrom": 35,
    "Mr. Game & Watch": 36,
    "Pit": 37,
    "Dark Pit": 38,
    "Zero Suit Samus": 39,
    "Wario": 41,
    "Snake": 42,
    "Ike": 43,
    "Pokemon Trainer": 44,
    "Diddy Kong": 45,
    "Lucas": 46,
    "Sonic": 47,
    "King DeDeDe": 48,
    "Olimar": 49,
    "Lucario": 50,
    "R.O.B.": 51,
    "Toon Link": 52,
    "Wolf": 53,
    "Villager": 54,
    "Mega Man": 55,
    "Wii-Fit": 56,
    "Rosalina & Luma": 57,
    "Little Mac": 58,
    "Greninja": 59,
    "Palutena": 60,
    "Pac-Man": 61,
    "Robin": 62,
    "Shulk": 63,
    "Bowser Jr.": 64,
    "Duck Hunt Duo": 65,
    "Ryu": 66,
    "Ken": 67,
    "Cloud": 68,
    "Corrin": 69,
    "Bayonetta": 70,
    "Inkling": 71,
    "Ridley": 72,
    "Simon": 73,
    "Richter": 74,
    "King K. Rool": 75,
    "Isabelle": 76,
    "Incineroar": 77,
    "Piranha Plant": 78,
    "Joker": 80,
    "Hero": 81,
    "Banjo & Kazooie": 82,
    "Terry": 83,
    "Byleth": 84,
    "Min Min": 85,
    "Steve": 86,
    "Sephiroth": 87,
    "Pyra/Mythra": 88,
    "Kazuya": 89,
    "Sora": 90,
    "Random": 91,
    "Mii Swordfighter": 96,
    "Mii Gunner": 97,
    "Mii Brawler": 98,
}
